<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <StartupObject></StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Database\Database.csproj" />
    <ProjectReference Include="..\LegoApi\LegoApi.csproj" />
    <ProjectReference Include="..\Logger\MyLogger.csproj" />
    <ProjectReference Include="..\Logic\Logic.csproj" />
  </ItemGroup>

</Project>
